name: Waka Readme

on:
  schedule:
    # Runs at 12am (UTC-5) in Colombia
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_UPDATED_DATE: "true"
          SHOW_PROFILE_VIEWS: "true"
          SYMBOL_VERSION: "1"
          
          
          
          
